[project]
name = "atreides"
version = "0.1.0"
description = "Atreides Python SDK"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prisma>=0.15.0",
]

[tool.uv]
dev-dependencies = [
    "vllm>=0.6.6.post1",
]
